### ISSUE TITLE
これは非常に有用なプロジェクトです。 私は試した。 とてもうまくいっています。 私が見つけた問題の 1 つは、高さと幅が異なるビデオを結合するときでした。 それは正しく機能していません。 解決策はありますか？

### ISSUE THREAD

**Issue by linslouis** [takusan23/AndroidMediaCodecVideoMerge#1]
これは非常に有用なプロジェクトです。 私は試した。 とてもうまくいっています。 私が見つけた問題の 1 つは、高さと幅が異なるビデオを結合するときでした。 それは正しく機能していません。 解決策はありますか？

**Comment by takusan23** [comment]
I'm sorry I'm late. 🙇‍♂️
If diff in video height and width, It use OpenGL. 👍
I pushed code example, see in this repository "use_opengl" branch. 👀 

Maybe helpful project : https://github.com/ypresto/android-transcoder/blob/master/lib/src/main/java/net/ypresto/androidtranscoder/engine/InputSurface.java

```
遅れてすいません。
動画の高さと幅が異なる場合は、OpenGL を使用します。
コード例をプッシュしました。このリポジトリの「use_opengl」ブランチを参照してください。

多分役に立つプロジェクト : https://github.com/ypresto/android-transcoder/blob/master/lib/src/main/java/net/ypresto/androidtranscoder/engine/InputSurface.java
```

**Comment by linslouis** [comment]
どうもありがとうございます
